version: '3.8'

services:
  # Servicio de la aplicación Laravel (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html 
    networks:
      - app-network

  # Servicio de PostgreSQL
  db:
    image: postgres:15 
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE} # Variables del .env de Laravel
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432" # Expone el puerto de PostgreSQL al host
    volumes:
      - pgsql_data:/var/lib/postgresql/data # Almacenamiento persistente
    networks:
      - app-network

  # Servicio de Nginx (Servidor web para servir la aplicación)
  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8080:80" # Expone el puerto 80 del host al contenedor
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf # Archivo de configuración
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgsql_data:
    driver: local